ctlo/blog/urls.py
from django.urls import re_path

from . import views

app_name = 'blog'

urlpatterns = [
    re_path('^$', views.index, name='index'),
    re_path('^login/', views.login_view),
    re_path('^signup/', views.register_view),
    re_path('^logout/', views.logout_view),
]

ctlo/ctlo/urls.py
from django.contrib import admin
from django.urls import re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # re_path('^blog/', include('blog.urls')),
    re_path('^ppe/', include('blog.urls')),
    re_path('^admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ctlo/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    isTeacher = models.BooleanField(default=False)

    @receiver
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

    def __str__(self):
        return self.user.username



class Class(models.Model):

    title = models.CharField(max_length=64)
    students = models.ManyToManyField(Profile, limit_choices_to={'isTeacher': False})

    def __str__(self):
        return self.title


class Question(models.Model):

    questionText = models.CharField(max_length=256, default='')

    choice_A = models.CharField(max_length=256, default='')
    choice_B = models.CharField(max_length=256, default='')
    choice_C = models.CharField(blank=True, max_length=256, default='')
    choice_D = models.CharField(blank=True, max_length=256, default='')

    answer = models.CharField(max_length=1, default='A')

    def __str__(self):
        return self.questionText
    

ctlo/portfolio/models.py
from django.db import models

# Create your models here.

ctlo/blog/forms.py
from django import forms

from django.contrib.auth import (
    authenticate,
    get_user_model
)

User = get_user_model()

class UserLoginForm(forms.Form):

    username = forms.CharField(help_text=False, label='Nom d\'utilisateur (prénom.nom)')
    password = forms.CharField(widget=forms.PasswordInput, label='Mot de passe') 

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:

            user = authenticate(username=username, password=password)

            if not user:
                raise forms.ValidationError('Nom d\'utilisateur ou mot de passe incorrect.')

        return super(UserLoginForm, self).clean(*args, **kwargs)

class UserRegisterForm(forms.ModelForm):

    email = forms.EmailField(label='Adresse email')
    password = forms.CharField(widget=forms.PasswordInput, label='Mot de passe')

    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'password'
        ]

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get('username')
        email = self.cleaned_data.get('email')

        email_qs = User.objects.filter(email=email) # email query set
        if email_qs.exists():
            raise forms.ValidationError('Cette adresse email est déjà utilisée.')

        username_qs = User.objects.filter(username=username) # username query set
        if username_qs.exists():
            raise forms.ValidationError('Ce nom d\'utilisateur est déjà utilisé. Cliquez ci-dessous pour vous connecter.')

        return super(UserRegisterForm, self).clean(*args, **kwargs)
        

ctlo/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Question

from django.contrib.auth import (
    authenticate,
    get_user_model,
    login,
    logout
)

from .forms import UserLoginForm, UserRegisterForm


@login_required
def index(request):

    if request.POST.get('newQuestion') != None:
        
        qId = request.POST.get('qId')
        q = get_object_or_404(Question, pk=qId)
        q.questionText = request.POST.get('newQuestion')
        
        submit = request.POST.get('submit')

        if 'Enregistrer' in submit:

            q.choice_A = request.POST.get('choiceA{}'.format(qId))
            q.choice_B = request.POST.get('choiceB{}'.format(qId))
            q.choice_C = request.POST.get('choiceC{}'.format(qId))
            q.choice_D = request.POST.get('choiceD{}'.format(qId))

            q.answer = request.POST.get('radAnswer')

            q.save()
        elif 'Annuler' in submit:
            questions = Question.objects.all().order_by('-id')
            return render(request, 'blog/index.html', {'questions': questions})

        else:
            q.delete()
    elif request.POST.get('verifAjouter') != None:
        Question.objects.create()
    questions = Question.objects.all().order_by('-id')
    return render(request, 'blog/index.html', {'questions': questions})


# def index(request):
    # return render(request, 'blog/index.html', {})

def login_view(request):

    next = request.GET.get('next')
    form = UserLoginForm(request.POST or None)

    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        login(request, user)

        if next:
            return redirect(next)
        return redirect('/ppe')
    
    context = {
        'form': form,
    }

    logout(request)
    return render(request, 'blog/login.html', context)

def register_view(request):

    next = request.GET.get('next')
    form = UserRegisterForm(request.POST or None)

    form.fields['username'].help_text = False
    form.fields['username'].label = 'Nom d\'utilisateur (prénom.nom)'

    if form.is_valid():
        user = form.save(commit=False)
        password = form.cleaned_data.get('password')
        user.set_password(password)
        user.first_name = user.username.split('.')[0].capitalize()
        user.last_name = user.username.split('.')[1].upper()
        user.save()
        new_user = authenticate(username=user.username, password=password)
        login(request, new_user)

        if next:
            return redirect(next)
        return redirect('/ppe', user)
    
    context = {
        'form': form,
    }

    logout(request)
    return render(request, 'blog/signup.html', context)

def logout_view(request):
    logout(request)
    return redirect('/ppe/login')

ctlo/portfolio/views.py
from django.shortcuts import render

# Create your views here.

ctlo/blog/templates/blog/base.html
{% load static %}

<! DOCTYPE html>

<html lang="fr">

    <head>
        <meta charset="utf-8">
        <title>{% block title %}PPE{% endblock %}</title>

        {% if request.path == '/ppe/' %}

            <link rel="stylesheet" type="text/css" href="{% static 'blog/css/index.css' %}">

        {% elif '/ppe/login' in request.path or '/ppe/signup' in request.path %}

            <link rel="stylesheet" type="text/css" href="{% static 'blog/css/auth.css' %}">

        {% endif %}

    
    
    </head>

    <body>

        {% block content %}

        {% endblock %}

    </body>

</html>

ctlo/blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block title %}Accueil - PPE{% endblock %}

{% block content %}

<h1>Bienvenue</h1>
<p>Bonjour, {{ user.first_name | title }} {{ user.last_name | upper }}. (<a href="/ppe/logout" id="switch"><em>Se déconnecter</em></a>)</p>
<hr>


{% if user.profile.isTeacher %}

<h2>Liste des questions:</h2>
<p>Pour effectuer des modifications merci de traiter les questions une par une.<p>

<form action="{% url 'blog:index' %}" method="post">
    {% csrf_token %}
    <input name="verifAjouter" type="text" style="visibility:hidden;display:None;">
    <input name="submit" class="addQuestion" type="submit" value="&#x2795; Ajouter">
</form>

{% for q in questions %}

<ul>
    <li class="item">

        <form action="{% url 'blog:index' %}" method="post">
            {% csrf_token %}
            
            <input value="{{ q.id }}" name="qId" type="text" style="display:none; visibility:hidden;">
            <input class="questionInput" value="{{ q.questionText }}" name="newQuestion" type="text">

            <ul class="subitem">
                <li>A) <input class="choiceInput" value="{{ q.choice_A }}" name="choiceA{{ q.id }}" type="text"></li>
                <li>B) <input class="choiceInput" value="{{ q.choice_B }}" name="choiceB{{ q.id }}" type="text"></li>
                <li>C) <input class="choiceInput" value="{{ q.choice_C }}" name="choiceC{{ q.id }}" type="text"></li>
                <li>D) <input class="choiceInput" value="{{ q.choice_D }}" name="choiceD{{ q.id }}" type="text"></li> 

                <span>&nbsp;&#x2705;)</span>
                <input name="radAnswer" type="radio" id="radio_{{ q.id }}A" value="A" {% if q.answer == 'A' %}checked{% endif %}>
                <label for="radio_{{ q.id }}A">A</label>

                <input name="radAnswer" type="radio" id="radio_{{ q.id }}B" value="B" {% if q.answer == 'B' %}checked{% endif %}>
                <label for="radio_{{ q.id }}B">B</label>

                <input name="radAnswer" type="radio" id="radio_{{ q.id }}C" value="C" {% if q.answer == 'C' %}checked{% endif %}>

                <label for="radio_{{ q.id }}C">C</label>
            
                <input name="radAnswer" type="radio" id="radio_{{ q.id }}D" value="D" {% if q.answer == 'D' %}checked{% endif %}>

                <label for="radio_{{ q.id }}D">D</label>
            </ul>

            <input name="submit" class="saveQuestion" type="submit" value="&#x2714; Enregistrer les changements">
            <input name="submit" class="cancelChanges" type="submit" value="&#x21A9; Annuler les changements">
            <input name="submit" class="delQuestion" type="submit" value="&nbsp;&#x2716;&nbsp;">
        </form>

    
    </li>
</ul>



{% endfor %}

{% else %}

{% endif %}






{% endblock %}

ctlo/blog/templates/blog/login.html
{% extends 'blog/base.html' %}

{% block title %}Connexion - PPE{% endblock %}

{% block content %}
<h1>&#x1F512; Connexion</h1>

<form method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="OK"/>
</form>
<a href="/ppe/signup" id="switch">Créer un compte</a>

{% endblock %}

ctlo/blog/templates/blog/signup.html
{% extends 'blog/base.html' %}

{% block title %}Créer un compte - PPE{% endblock %}

{% block content %}

<h1>&#x1F464; Créer un compte</h1>

<form method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="OK"/>
</form>
<a href="/ppe/login" id="switch">J'ai déjà un compte</a>

{% endblock %}